package app.snack.utils

enum class Screen {
    ONBOARDING,

    LOGIN,

    WELCOME,

    GOOGLE,
    FACEBOOK,

    SIGN_UP_EMAIL,
    SIGN_UP_CREATE_PASSWORD,
    SIGN_UP_CONFIRM_PASSWORD,

    SIGN_IN,
    SIGN_IN_RESTORE_PASSWORD,
    SIGN_IN_RESTORE_PASSWORD_DONE,

    MAIN,
    DASHBOARD,

    PROFILE,
    PROFILE_PAYOUT_REQUEST,
    PROFILE_PAYOUT_HISTORY,

    SETTINGS,
    SETTINGS_CHANGE_EMAIL,
    SETTINGS_CHANGE_PASSWORD,
    SETTINGS_LIMIT_TRAFFIC,
    SETTINGS_HELP,
    SETTINGS_HELP_DETAILS,
    SETTINGS_SUPPORT,
    SETTINGS_PRIVACY_POLICY,
    SETTINGS_TERMS,
}